/* Generated By:JavaCC: Do not edit this line. FunConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FunConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ASSIGN = 12;
  /** RegularExpression Id. */
  int GT = 13;
  /** RegularExpression Id. */
  int LT = 14;
  /** RegularExpression Id. */
  int EQ = 15;
  /** RegularExpression Id. */
  int LE = 16;
  /** RegularExpression Id. */
  int GE = 17;
  /** RegularExpression Id. */
  int NEQ = 18;
  /** RegularExpression Id. */
  int PLUS = 19;
  /** RegularExpression Id. */
  int MINUS = 20;
  /** RegularExpression Id. */
  int MULTIPLY = 21;
  /** RegularExpression Id. */
  int DIVIDE = 22;
  /** RegularExpression Id. */
  int REM = 23;
  /** RegularExpression Id. */
  int AND = 24;
  /** RegularExpression Id. */
  int OR = 25;
  /** RegularExpression Id. */
  int XOR = 26;
  /** RegularExpression Id. */
  int NOT = 27;
  /** RegularExpression Id. */
  int SEMICOLON = 28;
  /** RegularExpression Id. */
  int COMMA = 29;
  /** RegularExpression Id. */
  int LPAREN = 30;
  /** RegularExpression Id. */
  int RPAREN = 31;
  /** RegularExpression Id. */
  int LBRACKET = 32;
  /** RegularExpression Id. */
  int RBRACKET = 33;
  /** RegularExpression Id. */
  int LBRACE = 34;
  /** RegularExpression Id. */
  int RBRACE = 35;
  /** RegularExpression Id. */
  int DOT = 36;
  /** RegularExpression Id. */
  int BREAK = 37;
  /** RegularExpression Id. */
  int CLASS = 38;
  /** RegularExpression Id. */
  int CONSTRUCTOR = 39;
  /** RegularExpression Id. */
  int ELSE = 40;
  /** RegularExpression Id. */
  int EXTENDS = 41;
  /** RegularExpression Id. */
  int FOR = 42;
  /** RegularExpression Id. */
  int IF = 43;
  /** RegularExpression Id. */
  int NEW = 44;
  /** RegularExpression Id. */
  int PRINT = 45;
  /** RegularExpression Id. */
  int READ = 46;
  /** RegularExpression Id. */
  int RETURN = 47;
  /** RegularExpression Id. */
  int SUPER = 48;
  /** RegularExpression Id. */
  int INT = 49;
  /** RegularExpression Id. */
  int STRING = 50;
  /** RegularExpression Id. */
  int FLOAT = 51;
  /** RegularExpression Id. */
  int BOOLEAN = 52;
  /** RegularExpression Id. */
  int CHAR = 53;
  /** RegularExpression Id. */
  int float_constant = 54;
  /** RegularExpression Id. */
  int int_constant = 55;
  /** RegularExpression Id. */
  int DIGIT = 56;
  /** RegularExpression Id. */
  int LETTER = 57;
  /** RegularExpression Id. */
  int CONSTANT = 58;
  /** RegularExpression Id. */
  int boolean_constant = 59;
  /** RegularExpression Id. */
  int char_constant = 60;
  /** RegularExpression Id. */
  int IDENTIFIER = 61;
  /** RegularExpression Id. */
  int string_constant = 62;
  /** RegularExpression Id. */
  int TRUE = 63;
  /** RegularExpression Id. */
  int FALSE = 64;
  /** RegularExpression Id. */
  int null_constant = 65;
  /** RegularExpression Id. */
  int INVALID_LEXICAL = 66;
  /** RegularExpression Id. */
  int INVALID_CONST = 67;
  /** RegularExpression Id. */
  int INVALID_CHAR = 68;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int multilinecomment = 1;
  /** Lexical state. */
  int singlelinecomment = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\f\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 8>",
    "\"//\"",
    "<token of kind 10>",
    "<token of kind 11>",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"and\"",
    "\"or\"",
    "\"xor\"",
    "\"not\"",
    "\";\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\".\"",
    "\"break\"",
    "\"class\"",
    "\"constructor\"",
    "\"else\"",
    "\"extends\"",
    "\"for\"",
    "\"if\"",
    "\"new\"",
    "\"print\"",
    "\"read\"",
    "\"return\"",
    "\"super\"",
    "\"int\"",
    "\"string\"",
    "\"float\"",
    "\"boolean\"",
    "\"char\"",
    "<float_constant>",
    "<int_constant>",
    "<DIGIT>",
    "<LETTER>",
    "<CONSTANT>",
    "<boolean_constant>",
    "<char_constant>",
    "<IDENTIFIER>",
    "<string_constant>",
    "<TRUE>",
    "<FALSE>",
    "\"null\"",
    "<INVALID_LEXICAL>",
    "<INVALID_CONST>",
    "<INVALID_CHAR>",
  };

}
