/* Generated By:JavaCC: Do not edit this line. FunTokenManager.java */
package parser;

/** Token Manager. */
public class FunTokenManager implements FunConstants
{
int     countLexError = 0;

public int foundLexError() {
        return countLexError;
  }

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0, long active1)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x80000000L) != 0L)
            return 47;
         if ((active0 & 0x400000000L) != 0L)
            return 12;
         if ((active0 & 0x40000000000000L) != 0L || (active1 & 0x8L) != 0L)
         {
            jjmatchedKind = 74;
            return 37;
         }
         if ((active0 & 0xd7800d2000000000L) != 0L || (active1 & 0x81L) != 0L)
         {
            jjmatchedKind = 74;
            return 48;
         }
         if ((active0 & 0x300000000L) != 0L)
         {
            jjmatchedKind = 78;
            return 12;
         }
         if ((active0 & 0x20000000000L) != 0L)
         {
            jjmatchedKind = 74;
            return 30;
         }
         if ((active0 & 0x283ff0d000000000L) != 0L || (active1 & 0x4000076L) != 0L)
         {
            jjmatchedKind = 74;
            return 49;
         }
         return -1;
      case 1:
         if ((active0 & 0x300000000L) != 0L)
            return 12;
         if ((active0 & 0x4000050000000000L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 74;
               jjmatchedPos = 1;
            }
            return 48;
         }
         if ((active0 & 0x2ffffae000000000L) != 0L || (active1 & 0x40000ffL) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 74;
               jjmatchedPos = 1;
            }
            return 49;
         }
         if ((active0 & 0x9000001000000000L) != 0L)
            return 49;
         return -1;
      case 2:
         if ((active0 & 0xaf8fff0000000000L) != 0L || (active1 & 0x40000ffL) != 0L)
         {
            jjmatchedKind = 74;
            jjmatchedPos = 2;
            return 49;
         }
         if ((active0 & 0x4000000000000000L) != 0L)
         {
            jjmatchedKind = 74;
            jjmatchedPos = 2;
            return 48;
         }
         if ((active0 & 0x7000e000000000L) != 0L)
            return 49;
         return -1;
      case 3:
         if ((active0 & 0x4000000000000000L) != 0L)
         {
            jjmatchedKind = 74;
            jjmatchedPos = 3;
            return 48;
         }
         if ((active0 & 0xaf87f00000000000L) != 0L || (active1 & 0x400007aL) != 0L)
         {
            jjmatchedKind = 74;
            jjmatchedPos = 3;
            return 49;
         }
         if ((active0 & 0x80f0000000000L) != 0L || (active1 & 0x85L) != 0L)
            return 49;
         return -1;
      case 4:
         if ((active0 & 0xe185c00000000000L) != 0L || (active1 & 0x70L) != 0L)
         {
            jjmatchedKind = 74;
            jjmatchedPos = 4;
            return 49;
         }
         if ((active0 & 0xe02300000000000L) != 0L || (active1 & 0xaL) != 0L)
            return 49;
         return -1;
      case 5:
         if ((active0 & 0xa005c00000000000L) != 0L || (active1 & 0x10L) != 0L)
            return 49;
         if ((active0 & 0x4180000000000000L) != 0L || (active1 & 0x60L) != 0L)
         {
            jjmatchedKind = 74;
            jjmatchedPos = 5;
            return 49;
         }
         return -1;
      case 6:
         if ((active0 & 0x100000000000000L) != 0L || (active1 & 0x40L) != 0L)
         {
            jjmatchedKind = 74;
            jjmatchedPos = 6;
            return 49;
         }
         if ((active0 & 0x4080000000000000L) != 0L || (active1 & 0x20L) != 0L)
            return 49;
         return -1;
      case 7:
         if ((active0 & 0x100000000000000L) != 0L || (active1 & 0x40L) != 0L)
         {
            jjmatchedKind = 74;
            jjmatchedPos = 7;
            return 49;
         }
         return -1;
      case 8:
         if ((active1 & 0x40L) != 0L)
            return 49;
         if ((active0 & 0x100000000000000L) != 0L)
         {
            jjmatchedKind = 74;
            jjmatchedPos = 8;
            return 49;
         }
         return -1;
      case 9:
         if ((active0 & 0x100000000000000L) != 0L)
         {
            jjmatchedKind = 74;
            jjmatchedPos = 9;
            return 49;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0, long active1)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 33:
         jjmatchedKind = 35;
         return jjMoveStringLiteralDfa1_0(0x40000000L, 0x0L);
      case 38:
         return jjMoveStringLiteralDfa1_0(0x100000000L, 0x0L);
      case 40:
         return jjStopAtPos(0, 18);
      case 41:
         return jjStopAtPos(0, 19);
      case 42:
         return jjStopAtPos(0, 14);
      case 43:
         return jjStopAtPos(0, 12);
      case 44:
         return jjStopAtPos(0, 17);
      case 45:
         return jjStopAtPos(0, 13);
      case 46:
         return jjStartNfaWithStates_0(0, 31, 47);
      case 47:
         jjmatchedKind = 15;
         return jjMoveStringLiteralDfa1_0(0x240L, 0x0L);
      case 59:
         return jjStopAtPos(0, 16);
      case 60:
         jjmatchedKind = 24;
         return jjMoveStringLiteralDfa1_0(0x10000000L, 0x0L);
      case 61:
         jjmatchedKind = 26;
         return jjMoveStringLiteralDfa1_0(0x8000000L, 0x0L);
      case 62:
         jjmatchedKind = 25;
         return jjMoveStringLiteralDfa1_0(0x20000000L, 0x0L);
      case 91:
         return jjStopAtPos(0, 20);
      case 93:
         return jjStopAtPos(0, 21);
      case 94:
         return jjStartNfaWithStates_0(0, 34, 12);
      case 98:
         return jjMoveStringLiteralDfa1_0(0x400000000000000L, 0x81L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x300050000000000L, 0x0L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0xd000000000000000L, 0x0L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x80082000000000L, 0x0L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x40000000000000L, 0x8L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x20101000000000L, 0x0L);
      case 108:
         return jjMoveStringLiteralDfa1_0(0x8000000000L, 0x4L);
      case 110:
         return jjMoveStringLiteralDfa1_0(0x10000000000000L, 0x4000000L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0x200000000000L, 0x70L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0xc000000000000L, 0x0L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0x2003c04000000000L, 0x2L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x20000000000L, 0x0L);
      case 119:
         return jjMoveStringLiteralDfa1_0(0x800000000000000L, 0x0L);
      case 123:
         return jjStopAtPos(0, 22);
      case 124:
         return jjMoveStringLiteralDfa1_0(0x200000000L, 0x0L);
      case 125:
         return jjStopAtPos(0, 23);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0, long active1)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1);
      return 1;
   }
   switch(curChar)
   {
      case 38:
         if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(1, 32, 12);
         break;
      case 42:
         if ((active0 & 0x40L) != 0L)
            return jjStopAtPos(1, 6);
         break;
      case 47:
         if ((active0 & 0x200L) != 0L)
            return jjStopAtPos(1, 9);
         break;
      case 61:
         if ((active0 & 0x8000000L) != 0L)
            return jjStopAtPos(1, 27);
         else if ((active0 & 0x10000000L) != 0L)
            return jjStopAtPos(1, 28);
         else if ((active0 & 0x20000000L) != 0L)
            return jjStopAtPos(1, 29);
         else if ((active0 & 0x40000000L) != 0L)
            return jjStopAtPos(1, 30);
         break;
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x50000000000L, active1, 0L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x401c408000000000L, active1, 0L);
      case 102:
         if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 36, 49);
         break;
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x800020000000000L, active1, 0x2L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x8L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x200080000000000L, active1, 0L);
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x20102000000000L, active1, 0L);
      case 111:
         if ((active0 & 0x1000000000000000L) != 0L)
         {
            jjmatchedKind = 60;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x8140000000000000L, active1, 0x84L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x400200000000000L, active1, 0x60L);
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0x1800000000000L, active1, 0L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x2004000000000L, active1, 0x4000010L);
      case 119:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000000000000L, active1, 0L);
      case 120:
         return jjMoveStringLiteralDfa2_0(active0, 0x80000000000000L, active1, 0L);
      case 121:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x1L);
      case 124:
         if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(1, 33, 12);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(0, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, active1);
      return 2;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x208800000000000L, active1, 0L);
      case 98:
         if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 38, 49);
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x10L);
      case 100:
         if ((active0 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 37, 49);
         break;
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x400020000000000L, active1, 0L);
      case 102:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000000000000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x2800200000000000L, active1, 0x20L);
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x410000000000L, active1, 0x4000000L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x100000000000000L, active1, 0xcL);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0xc2L);
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x2100000000000L, active1, 0L);
      case 114:
         if ((active0 & 0x40000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 54, 49);
         return jjMoveStringLiteralDfa3_0(active0, 0x1000000000000L, active1, 0L);
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0xc0000000000L, active1, 0L);
      case 116:
         if ((active0 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 39, 49);
         else if ((active0 & 0x20000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 53, 49);
         return jjMoveStringLiteralDfa3_0(active0, 0x84000000000000L, active1, 0x1L);
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000000000000L, active1, 0L);
      case 119:
         if ((active0 & 0x10000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 52, 49);
         break;
      default :
         break;
   }
   return jjStartNfa_0(1, active0, active1);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(1, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, active1);
      return 3;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x4400000000000000L, active1, 0x8L);
      case 98:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000000000000000L, active1, 0L);
      case 100:
         if ((active0 & 0x8000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 51, 49);
         break;
      case 101:
         if ((active0 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 42, 49);
         else if ((active0 & 0x80000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 43, 49);
         else if ((active1 & 0x1L) != 0L)
            return jjStartNfaWithStates_0(3, 64, 49);
         return jjMoveStringLiteralDfa4_0(active0, 0x82400000000000L, active1, 0L);
      case 103:
         if ((active1 & 0x4L) != 0L)
            return jjStartNfaWithStates_0(3, 66, 49);
         break;
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000000000000L, active1, 0L);
      case 108:
         if ((active0 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 40, 49);
         else if ((active1 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(3, 71, 49);
         else if ((active1 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(3, 74, 49);
         return jjMoveStringLiteralDfa4_0(active0, 0x800000000000000L, active1, 0x10L);
      case 110:
         if ((active0 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 41, 49);
         return jjMoveStringLiteralDfa4_0(active0, 0x200000000000L, active1, 0L);
      case 114:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x2L);
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x300000000000000L, active1, 0L);
      case 116:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000800000000000L, active1, 0x40L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x4100000000000L, active1, 0L);
      case 118:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x20L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0, active1);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(2, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, active1);
      return 4;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x20L);
      case 99:
         return jjMoveStringLiteralDfa5_0(active0, 0x2000400000000000L, active1, 0L);
      case 101:
         if ((active0 & 0x800000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 59, 49);
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x40L);
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x800000000000L, active1, 0x10L);
      case 107:
         if ((active0 & 0x400000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 58, 49);
         break;
      case 108:
         if ((active1 & 0x8L) != 0L)
            return jjStartNfaWithStates_0(4, 67, 49);
         return jjMoveStringLiteralDfa5_0(active0, 0x8000000000000000L, active1, 0L);
      case 110:
         return jjMoveStringLiteralDfa5_0(active0, 0x81000000000000L, active1, 0L);
      case 114:
         if ((active0 & 0x2000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 49, 49);
         return jjMoveStringLiteralDfa5_0(active0, 0x4000000000000L, active1, 0L);
      case 115:
         if ((active0 & 0x200000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 57, 49);
         break;
      case 116:
         if ((active0 & 0x100000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 44, 49);
         else if ((active0 & 0x200000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 45, 49);
         else if ((active1 & 0x2L) != 0L)
            return jjStartNfaWithStates_0(4, 65, 49);
         return jjMoveStringLiteralDfa5_0(active0, 0x100000000000000L, active1, 0L);
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000000000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0, active1);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(3, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0, active1);
      return 5;
   }
   switch(curChar)
   {
      case 99:
         if ((active0 & 0x800000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 47, 49);
         else if ((active1 & 0x10L) != 0L)
            return jjStartNfaWithStates_0(5, 68, 49);
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x40L);
      case 100:
         return jjMoveStringLiteralDfa6_0(active0, 0x80000000000000L, active1, 0L);
      case 101:
         if ((active0 & 0x8000000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 63, 49);
         break;
      case 103:
         if ((active0 & 0x1000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 48, 49);
         break;
      case 104:
         if ((active0 & 0x2000000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 61, 49);
         break;
      case 108:
         return jjMoveStringLiteralDfa6_0(active0, 0x4000000000000000L, active1, 0L);
      case 110:
         if ((active0 & 0x4000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 50, 49);
         break;
      case 114:
         return jjMoveStringLiteralDfa6_0(active0, 0x100000000000000L, active1, 0L);
      case 116:
         if ((active0 & 0x400000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 46, 49);
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x20L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0, active1);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(4, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0, active1);
      return 6;
   }
   switch(curChar)
   {
      case 101:
         if ((active1 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(6, 69, 49);
         break;
      case 115:
         if ((active0 & 0x80000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 55, 49);
         break;
      case 116:
         if ((active0 & 0x4000000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 62, 49);
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x40L);
      case 117:
         return jjMoveStringLiteralDfa7_0(active0, 0x100000000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0, active1);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(5, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0, active1);
      return 7;
   }
   switch(curChar)
   {
      case 99:
         return jjMoveStringLiteralDfa8_0(active0, 0x100000000000000L, active1, 0L);
      case 101:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x40L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0, active1);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(6, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0, active1);
      return 8;
   }
   switch(curChar)
   {
      case 100:
         if ((active1 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(8, 70, 49);
         break;
      case 116:
         return jjMoveStringLiteralDfa9_0(active0, 0x100000000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0, active1);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(7, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0, 0L);
      return 9;
   }
   switch(curChar)
   {
      case 111:
         return jjMoveStringLiteralDfa10_0(active0, 0x100000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0, 0L);
}
private int jjMoveStringLiteralDfa10_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0, 0L);
      return 10;
   }
   switch(curChar)
   {
      case 114:
         if ((active0 & 0x100000000000000L) != 0L)
            return jjStartNfaWithStates_0(10, 56, 49);
         break;
      default :
         break;
   }
   return jjStartNfa_0(9, active0, 0L);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 47;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 47:
                  if ((0x840040d8ffffc9ffL & l) != 0L)
                  {
                     if (kind > 91)
                        kind = 91;
                     jjCheckNAdd(12);
                  }
                  else if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 84)
                        kind = 84;
                     jjCheckNAdd(26);
                  }
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(22, 23);
                  break;
               case 0:
                  if ((0x840040d8ffffc9ffL & l) != 0L)
                  {
                     if (kind > 91)
                        kind = 91;
                     jjCheckNAdd(12);
                  }
                  else if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 73)
                        kind = 73;
                     jjCheckNAddStates(0, 9);
                  }
                  else if (curChar == 34)
                     jjCheckNAddStates(10, 13);
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(5, 6);
                  else if (curChar == 46)
                     jjCheckNAddTwoStates(22, 26);
                  else if (curChar == 39)
                     jjstateSet[jjnewStateCnt++] = 10;
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(3, 4);
                  if ((0x3000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(7, 8);
                  break;
               case 30:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 74)
                        kind = 74;
                     jjCheckNAddTwoStates(1, 2);
                  }
                  else if (curChar == 36)
                  {
                     if (kind > 74)
                        kind = 74;
                  }
                  break;
               case 49:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 74)
                        kind = 74;
                     jjCheckNAddTwoStates(1, 2);
                  }
                  else if (curChar == 36)
                  {
                     if (kind > 74)
                        kind = 74;
                  }
                  break;
               case 48:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(5, 6);
                  else if (curChar == 36)
                  {
                     if (kind > 74)
                        kind = 74;
                  }
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 74)
                        kind = 74;
                     jjCheckNAddTwoStates(1, 2);
                  }
                  break;
               case 37:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(5, 6);
                  else if (curChar == 36)
                  {
                     if (kind > 74)
                        kind = 74;
                  }
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 74)
                        kind = 74;
                     jjCheckNAddTwoStates(1, 2);
                  }
                  break;
               case 1:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 74)
                     kind = 74;
                  jjCheckNAddTwoStates(1, 2);
                  break;
               case 2:
                  if (curChar == 36 && kind > 74)
                     kind = 74;
                  break;
               case 3:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(3, 4);
                  break;
               case 5:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(5, 6);
                  break;
               case 7:
                  if ((0x3000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(7, 8);
                  break;
               case 9:
                  if (curChar == 39)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 10:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 11:
                  if (curChar == 39 && kind > 85)
                     kind = 85;
                  break;
               case 12:
                  if ((0x840040d8ffffc9ffL & l) == 0L)
                     break;
                  if (kind > 91)
                     kind = 91;
                  jjCheckNAdd(12);
                  break;
               case 13:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAddStates(0, 9);
                  break;
               case 14:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAdd(14);
                  break;
               case 15:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 79)
                     kind = 79;
                  jjCheckNAdd(15);
                  break;
               case 16:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 80)
                     kind = 80;
                  jjCheckNAdd(16);
                  break;
               case 17:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 81)
                     kind = 81;
                  jjCheckNAdd(17);
                  break;
               case 18:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(18, 19);
                  break;
               case 20:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(20, 21);
                  break;
               case 21:
                  if (curChar == 46)
                     jjCheckNAdd(22);
                  break;
               case 22:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(22, 23);
                  break;
               case 24:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(24, 25);
                  break;
               case 25:
                  if (curChar == 46)
                     jjCheckNAdd(26);
                  break;
               case 26:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 84)
                     kind = 84;
                  jjCheckNAdd(26);
                  break;
               case 41:
                  if (curChar == 46)
                     jjCheckNAddTwoStates(22, 26);
                  break;
               case 42:
                  if (curChar == 34)
                     jjCheckNAddStates(10, 13);
                  break;
               case 43:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                     jjCheckNAddTwoStates(43, 44);
                  break;
               case 44:
                  if (curChar == 34 && kind > 86)
                     kind = 86;
                  break;
               case 45:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                     jjCheckNAddTwoStates(45, 46);
                  break;
               case 46:
                  if ((0x2400L & l) != 0L)
                     kind = 92;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 47:
               case 12:
                  if ((0xd0000001d0000001L & l) == 0L)
                     break;
                  if (kind > 91)
                     kind = 91;
                  jjCheckNAdd(12);
                  break;
               case 0:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 74)
                        kind = 74;
                     jjCheckNAddTwoStates(1, 2);
                  }
                  else if ((0xd0000001d0000001L & l) != 0L)
                  {
                     if (kind > 91)
                        kind = 91;
                     jjCheckNAdd(12);
                  }
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(5, 6);
                  else if ((0x10000000100L & l) != 0L)
                  {
                     if (kind > 81)
                        kind = 81;
                  }
                  else if (curChar == 116)
                     jjAddStates(14, 15);
                  if (curChar == 102)
                     jjAddStates(16, 17);
                  break;
               case 30:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 74)
                        kind = 74;
                     jjCheckNAddTwoStates(1, 2);
                  }
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 32;
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 29;
                  break;
               case 49:
               case 1:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 74)
                     kind = 74;
                  jjCheckNAddTwoStates(1, 2);
                  break;
               case 48:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 74)
                        kind = 74;
                     jjCheckNAddTwoStates(1, 2);
                  }
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(5, 6);
                  else if ((0x10000000100L & l) != 0L)
                  {
                     if (kind > 81)
                        kind = 81;
                  }
                  break;
               case 37:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 74)
                        kind = 74;
                     jjCheckNAddTwoStates(1, 2);
                  }
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(5, 6);
                  else if ((0x10000000100L & l) != 0L)
                  {
                     if (kind > 81)
                        kind = 81;
                  }
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 39;
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 36;
                  break;
               case 4:
                  if ((0x800000008000L & l) != 0L && kind > 81)
                     kind = 81;
                  break;
               case 5:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(5, 6);
                  break;
               case 6:
                  if ((0x10000000100L & l) != 0L && kind > 81)
                     kind = 81;
                  break;
               case 8:
                  if ((0x400000004L & l) != 0L && kind > 81)
                     kind = 81;
                  break;
               case 10:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 19:
                  if ((0x100000001000L & l) != 0L && kind > 82)
                     kind = 82;
                  break;
               case 23:
                  if ((0x4000000040L & l) != 0L && kind > 83)
                     kind = 83;
                  break;
               case 27:
                  if (curChar == 116)
                     jjAddStates(14, 15);
                  break;
               case 28:
                  if (curChar == 101 && kind > 77)
                     kind = 77;
                  break;
               case 29:
                  if (curChar == 117)
                     jjCheckNAdd(28);
                  break;
               case 31:
                  if (curChar == 101 && kind > 87)
                     kind = 87;
                  break;
               case 32:
                  if (curChar == 117)
                     jjCheckNAdd(31);
                  break;
               case 33:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 32;
                  break;
               case 34:
                  if (curChar == 102)
                     jjAddStates(16, 17);
                  break;
               case 35:
                  if (curChar == 115)
                     jjCheckNAdd(28);
                  break;
               case 36:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 38:
                  if (curChar == 115)
                     jjCheckNAdd(31);
                  break;
               case 39:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 40:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 39;
                  break;
               case 43:
                  jjAddStates(18, 19);
                  break;
               case 45:
                  jjAddStates(20, 21);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 47:
               case 12:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 91)
                     kind = 91;
                  jjCheckNAdd(12);
                  break;
               case 0:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 91)
                     kind = 91;
                  jjCheckNAdd(12);
                  break;
               case 43:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(18, 19);
                  break;
               case 45:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(20, 21);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 47 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
private int jjMoveStringLiteralDfa0_2()
{
   return jjMoveNfa_2(0, 0);
}
private int jjMoveNfa_2(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 1;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x2400L & l) != 0L)
                     kind = 10;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 1 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
private int jjMoveStringLiteralDfa0_1()
{
   switch(curChar)
   {
      case 42:
         return jjMoveStringLiteralDfa1_1(0x80L);
      default :
         return 1;
   }
}
private int jjMoveStringLiteralDfa1_1(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      return 1;
   }
   switch(curChar)
   {
      case 47:
         if ((active0 & 0x80L) != 0L)
            return jjStopAtPos(1, 7);
         break;
      default :
         return 2;
   }
   return 2;
}
static final int[] jjnextStates = {
   14, 15, 16, 17, 18, 19, 20, 21, 24, 25, 43, 44, 45, 46, 30, 33, 
   37, 40, 43, 44, 45, 46, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, "\53", 
"\55", "\52", "\57", "\73", "\54", "\50", "\51", "\133", "\135", "\173", "\175", 
"\74", "\76", "\75", "\75\75", "\74\75", "\76\75", "\41\75", "\56", "\46\46", 
"\174\174", "\136", "\41", "\151\146", "\145\156\144", "\163\165\142", "\154\145\164", 
"\143\141\154\154", "\164\150\145\156", "\143\141\163\145", "\145\154\163\145", 
"\151\156\160\165\164", "\160\162\151\156\164", "\163\145\154\145\143\164", 
"\163\164\141\164\151\143", "\163\164\162\151\156\147", "\163\165\160\145\162", 
"\162\145\164\165\162\156", "\162\145\141\144", "\156\145\167", "\151\156\164", "\146\157\162", 
"\145\170\164\145\156\144\163", "\143\157\156\163\164\162\165\143\164\157\162", "\143\154\141\163\163", 
"\142\162\145\141\153", "\167\150\151\154\145", "\144\157", "\163\167\151\164\143\150", 
"\144\145\146\141\165\154\164", "\144\157\165\142\154\145", "\142\171\164\145", "\163\150\157\162\164", 
"\154\157\156\147", "\146\151\156\141\154", "\160\165\142\154\151\143", 
"\160\162\151\166\141\164\145", "\160\162\157\164\145\143\164\145\144", "\142\157\157\154", null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, "\156\165\154\154", null, null, };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
   "multilinecomment",
   "singlelinecomment",
};

/** Lex State array. */
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, -1, -1, 1, 0, -1, 2, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
};
static final long[] jjtoToken = {
   0xfffffffffffff001L, 0x4ffe6ffL, 
};
static final long[] jjtoSkip = {
   0xffeL, 0x18000000L, 
};
static final long[] jjtoSpecial = {
   0x0L, 0x18000000L, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[47];
private final int[] jjstateSet = new int[94];
protected char curChar;
/** Constructor. */
public FunTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public FunTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 47; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 3 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      matchedToken.specialToken = specialToken;
      return matchedToken;
   }

   switch(curLexState)
   {
     case 0:
       try { input_stream.backup(0);
          while (curChar <= 32 && (0x100003600L & (1L << curChar)) != 0L)
             curChar = input_stream.BeginToken();
       }
       catch (java.io.IOException e1) { continue EOFLoop; }
       jjmatchedKind = 0x7fffffff;
       jjmatchedPos = 0;
       curPos = jjMoveStringLiteralDfa0_0();
       if (jjmatchedPos == 0 && jjmatchedKind > 78)
       {
          jjmatchedKind = 78;
       }
       break;
     case 1:
       jjmatchedKind = 0x7fffffff;
       jjmatchedPos = 0;
       curPos = jjMoveStringLiteralDfa0_1();
       if (jjmatchedPos == 0 && jjmatchedKind > 8)
       {
          jjmatchedKind = 8;
       }
       break;
     case 2:
       jjmatchedKind = 0x7fffffff;
       jjmatchedPos = 0;
       curPos = jjMoveStringLiteralDfa0_2();
       if (jjmatchedPos == 0 && jjmatchedKind > 11)
       {
          jjmatchedKind = 11;
       }
       break;
   }
     if (jjmatchedKind != 0x7fffffff)
     {
        if (jjmatchedPos + 1 < curPos)
           input_stream.backup(curPos - jjmatchedPos - 1);
        if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
        {
           matchedToken = jjFillToken();
           matchedToken.specialToken = specialToken;
       if (jjnewLexState[jjmatchedKind] != -1)
         curLexState = jjnewLexState[jjmatchedKind];
           return matchedToken;
        }
        else
        {
           if ((jjtoSpecial[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
           {
              matchedToken = jjFillToken();
              if (specialToken == null)
                 specialToken = matchedToken;
              else
              {
                 matchedToken.specialToken = specialToken;
                 specialToken = (specialToken.next = matchedToken);
              }
           }
         if (jjnewLexState[jjmatchedKind] != -1)
           curLexState = jjnewLexState[jjmatchedKind];
           continue EOFLoop;
        }
     }
     int error_line = input_stream.getEndLine();
     int error_column = input_stream.getEndColumn();
     String error_after = null;
     boolean EOFSeen = false;
     try { input_stream.readChar(); input_stream.backup(1); }
     catch (java.io.IOException e1) {
        EOFSeen = true;
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
        if (curChar == '\n' || curChar == '\r') {
           error_line++;
           error_column = 0;
        }
        else
           error_column++;
     }
     if (!EOFSeen) {
        input_stream.backup(1);
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
     }
     throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
